config/routes.rb
Rails.application.routes.draw do

  resources :cart, only: [:index, :create, :destroy, :update]

  namespace :api do
    resources :books, only: [:index, :show, :create, :update, :destroy]
  end
  

  get 'register', to: 'user#new'
  get 'login', to: 'user#login_form', as: :login
  post 'user/login', to: 'user#login'
  post 'user/create'
  get 'user/logout'

  get 'book/:id', to: 'book#show', as: 'book'
  get 'book/new'
  get 'book/user'
  get 'book/review'
  
  root to: "book#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.total_price(cart_items)
    total_price = cart_items.sum { |cart_item| cart_item.quantity * cart_item.book.price }
    total_price
  end

end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews
    has_many :order_items
  end  

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validate :user_must_be_regular_user
  
  def self.book_already_in_cart?(user_id, book_id)
    where(user_id: user_id, book_id: book_id).exists?
  end

  private

  def user_must_be_regular_user
    unless user.user_role == 'user'
      errors.add(:user_id, "must belong to a regular user")
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :book
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_presence_of :email

    # after_initialize :set_defaults

    # def set_defaults
    #     self.user_role ||= "user"
    # end
end

app/controllers/api/books_controller.rb
module Api
  class BooksController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_book, only: [:show, :update, :destroy]
    
    include AuthenticateUser
    before_action :authorize_admin, only: [:new, :edit, :destroy]
    before_action :authenticate_request

    def index
      @books = Book.all
      render json: @books
    end

    def show
      render json: @book
    end

    def create
      @book = Book.new(book_params)
      if @book.save
        render json: @book, status: :created
      else
        render json: @book.errors, status: :unprocessable_entity
      end
    end

    def update
      if @book.update(book_params)
        render json: @book
      else
        render json: @book.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @book.destroy
      head :no_content
    end

    private

    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:author, :title, :genre, :description, :cover_image, :quantity, :price)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :user
  
    def user
      @role = JWT.decode(session[:user], 'abcd', true, algorithm: 'HS256')[0]["user_role"] unless !session[:user]
      @id = JWT.decode(session[:user], 'abcd', true, algorithm: 'HS256')[0]["user_id"] unless !session[:user]
      @token = (session[:user].to_json.html_safe if session[:user].to_json)
    end
  end
  

app/controllers/book_controller.rb
class BookController < ApplicationController
  
  include AuthenticateUser

  before_action :authorize_admin, only: [:new, :edit, :destroy]

  def index
    payload = { user_id: 1, user_role: "guest" }
    session[:user] = JWT.encode(payload, 'abcd', 'HS256') unless session[:user]
  end
  
  def show
   @book_id = params[:id]
  end
  
  def new
  end
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  skip_before_action :verify_authenticity_token

def index
  user_id = JWT.decode(session[:user], 'abcd', true, algorithm: 'HS256')[0]["user_id"]
  @cart_items = Cart.where(user_id: user_id).includes(:book)
  @total = Cart.total_price(@cart_items)
end

def create
  book_id = params[:book_id]
  user_id = params[:user_id]
  quantity = params[:quantity]

  if Cart.book_already_in_cart?(user_id, book_id)
    cart_item = Cart.find_by(user_id: user_id, book_id: book_id)
    if cart_item.quantity != quantity
      cart_item.update(quantity: quantity)
      render json: { message: 'Item quantity updated in cart' }, status: :ok
    else
      render json: { message: 'Item already in cart with the same quantity' }, status: :ok
    end
    redirect_to cart_index_path

  else
    cart_item = Cart.new(book_id: book_id, user_id: user_id, quantity: quantity)
    if cart_item.save
      render json: { message: 'Item added to cart successfully' }, status: :ok
    else
      render json: { error: 'Failed to add item to cart' }, status: :unprocessable_entity
    end
  end
end

def destroy
  Cart.find(params[:id]).destroy
  redirect_to cart_index_path
end

def update
  Cart.find(params[:id]).update(quantity: params[:quantity])
end

end

app/controllers/concerns/authenticate_user.rb
module AuthenticateUser
    extend ActiveSupport::Concern

    def authorize_admin
      redirect_to root_path, alert: 'Access denied.' unless current_user == 'admin'
    end

    def authenticate_request
      token = request.headers['Authorization'].split(' ').last
      decoded_token = JWT.decode(token, 'abcd', true, algorithm: 'HS256')
    rescue JWT::DecodeError, ActiveRecord::RecordNotFound
      render json: { error: 'Unauthorized' }, status: :unauthorized
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
    @user.user_role = params[:role] == 'admin' ? 'admin' : 'user'
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      payload = { user_id: @user.id, user_role: @user.user_role }
      session[:user] = JWT.encode(payload, 'abcd', 'HS256') 

      redirect_to root_path, notice: "Logged in successfully"
    else
      flash.now[:alert] = "Invalid email or password."
      redirect_to register_path
    end
  end
  

  def login_form
    @user = User.new
  end

  def logout
    session[:user] = nil
    redirect_to root_path, notice: "Logged out successfully"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user] = JWT.encode({ user_id: @user.id, user_role: @user.user_role }, 'abcd', 'HS256')
      redirect_to root_path, notice: "Registration successful. Welcome!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :user_role)
  end
end

app/helpers/api/books_helper.rb
module Api::BooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/book/index.html.erb
<%= render 'partials/navbar', role: @role %>
<div class="container"></div>

<%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
<script>
  function getBook(id) {
    window.location.href = `/book/${id}`;
  }

  $(document).ready(function() {
    var authToken = '<%= @token %>';
    var container = $('.container');

    fetch('http://localhost:3000/api/books', {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${authToken}`
      }
    })
    .then(response => response.json())
    .then(data => {
      console.log(data);
      const booksHtml = data.map(book => `
        <div class="book" onclick="getBook(${book.id})">
          <img src="${book.cover_image}" />
          <div class="book_info">
            <p>${book.title}</p>
            <p>${book.author}</p>
            <p>${book.price}</p>
            <button onclick="abc(${book.id})">add to cart</button>
          </div>
        </div>
      `).join('');
      container.html(booksHtml);
    })
    .catch(error => {
      console.error('Error:', error);
    });
  });

  function abc(book_id){
    console.log("hai");
    if ("<%= @role != 'user' %>") {
      fetch('/cart', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          book_id: book_id,
          user_id: <%= JWT.decode(session[:user], 'abcd', true, algorithm: 'HS256')[0]["user_id"]%>,
          quantity: 1
        })
      })
      .then(() => {
        console.log("added to cart");
        window.location.href = '<%= cart_index_path %>';
      })
      .catch((err) => {
        console.log(err);
      });
    } else {
      window.location.href = '<%= login_path %>';
    }
  }
</script>

app/views/book/new.html.erb
<div class="form-container">
  <input id="author" type="text" placeholder="Author">
  <input id="title" type="text" placeholder="Title">
  <input id="genre" type="text" placeholder="Genre">
  <input id="description" type="text" placeholder="Description">
  <input id="cover_image" type="text" placeholder="Cover Image URL">
  <button id="submit-button">Submit</button>
</div>

<script>
    var authToken = <%= @token %>
    const submitButton = document.getElementById('submit-button');
    const formContainer = document.querySelector('.form-container');
    
    submitButton.addEventListener('click', () => {
      const author = document.getElementById('author').value;
      const title = document.getElementById('title').value;
      const genre = document.getElementById('genre').value;
      const description = document.getElementById('description').value;
      const coverImage = document.getElementById('cover_image').value;
      
      const formData = {
        author: author,
        title: title,
        genre: genre,
        description: description,
        cover_image: coverImage
      };
      
      fetch('http://localhost:3000/api/books', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${authToken}`
        },
        body: JSON.stringify(formData)
      })
      .then(response => response.json())
      .then(data => {
        console.log('Book created:', data);
        // Handle success, e.g., show a success message to the user
      })
      .catch(error => {
        console.error('Error:', error);
        // Handle error, e.g., show an error message to the user
      });
    });
  
</script>

app/views/book/show.html.erb
<%= render 'partials/navbar', role: @role %>

<div class="show_book"></div>

<div class="flex">
  <div class="delete_book">
    <%= button_tag "delete book" unless @role !=  "admin" %>
  </div>
  <div class="edit_book">
    <%= button_tag "edit book" unless @role !=  "admin" %>
  </div>
  <p class="addToCart">add to cart</p>
</div>
 
<script>
  const authToken = <%= @token %>
  const book_id = <%= @book_id %>
  const delete_book = document.querySelector(".delete_book")
  const edit_book = document.querySelector(".edit_book")
  const container = document.querySelector(".show_book");
  var temp_data = {}
  var quantity = 1

  fetch(`http://localhost:3000/api/books/${book_id}`, {
      method: 'GET',
      headers: {'Authorization': `Bearer ${authToken}`}
    })
    .then(response => response.json())
    .then(data => {
      const booksHtml =
      `<div>
          <img src="${data.cover_image}" />
          <div class="data_info">
            <p>${data.title}</p>
            <p>${data.author}</p>
            <p>${data.description}</p>
            <p>${data.genre}</p>
            quantity: <input class="quantity" type="number" value=${quantity} name="quantity"/>
            price: <p>${data.price}</p>
          </div>
      </div>`

      container.innerHTML = booksHtml;
      document.querySelector(".quantity").addEventListener("input",()=>{
        quantity = document.querySelector(".quantity").value
      })

      temp_data = {...data}
      })
    .catch(error => {
      console.error('Error:', error)
    });

  delete_book.addEventListener("click",()=>{
    fetch(`http://localhost:3000/api/books/${book_id}`, {
      method: 'DELETE',
      headers: {'Authorization': `Bearer ${authToken}`}
    })
    .then(()=>{
      window.location.href = '<%= root_path %>';
    })
    .catch((error)=>{
      console.log(error)
    })
  })

  edit_book.addEventListener("click", () => {
    const booksHtml =
    `<form id="editForm">
        <input id="cover_image" value="${temp_data.cover_image}" type="text"/>
        <div class="temp_data_info">
          <input id="title" value="${temp_data.title}" type="text"/>
          <input id="author" value="${temp_data.author}" type="text" />
          <input id="description" value="${temp_data.description}" type="text" />
          <input id="genre" value="${temp_data.genre}" type="text"/>
          <input id="quantity" value="${temp_data.quantity}" type="number"/>
          <input id="price" value="${temp_data.price}" type="number"/>
        </div>
        <button type="submit" value="Submit">update book</button>
    </form>`

    container.innerHTML = booksHtml;
    edit_book.style.display = "none"
    const editForm = document.getElementById('editForm');
    editForm.addEventListener('submit', function(event) {
      event.preventDefault(); 
      const formData = {
        cover_image: document.getElementById('cover_image').value,
        title: document.getElementById('title').value,
        author: document.getElementById('author').value,
        description: document.getElementById('description').value,
        genre: document.getElementById('genre').value,
        price: document.getElementById('price').value,
        quantity: document.getElementById('quantity').value
      };
      fetch(`http://localhost:3000/api/books/${book_id}`, {
        method: 'PATCH',
        headers: {
          'Authorization': `Bearer ${authToken}`,
          'Content-Type': 'application/json' // Specify the content type
        },
        body: JSON.stringify(formData) // Convert formData to JSON string
      })
      .then(response => {
        if (response.ok) {
          window.location.href = `/book/${book_id}`;
          } else {
          console.log("Error updating book");
        }
      })
      .catch(error => {
        console.error('Error:', error);
        });
        
        });
        });
        
        
  const addToCart = document.querySelector(".addToCart")
  
  addToCart.addEventListener("click", ()=>{
    console.log
    if('<%= @role %>' != "guest"){
          const formData2 = {
            book_id: `${book_id}`,
            user_id: <%= JWT.decode(session[:user], 'abcd', true, algorithm: 'HS256')[0]["user_id"]%>,
            quantity: `${quantity}`
            };

          fetch('/cart', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData2)
          })
          .then(()=>{
            console.log("added to cart");
            window.location.href = '<%= cart_index_path %>';
          })
          .catch((err)=>{
            console.log(err)
          })
    }
  else{
   window.location.href = '<%= login_path %>';
  }


  })
</script>

app/views/cart/index.html.erb
<%= render 'partials/navbar', role: @role %>

<h1>Your Cart</h1>

<div id="cart-items">
  <% @cart_items.each do |cart_item| %>
    <div class="container" data-cart-id="<%= cart_item.id %>">
      <%= image_tag cart_item.book.cover_image %>
      <div>
        <p><%= cart_item.book.title %></p>
        <p><%= cart_item.book.author %></p>
        <input class="quantity_input" value="<%= cart_item.quantity %>" name="quantity" type="number"/>
        <p>price: <%= number_to_currency(cart_item.book.price * cart_item.quantity, unit: "₹", precision: 2, delimiter: ",", format: "%u%n") %></p>
      </div>
     
      <div>
        <%= link_to "delete", cart_path(cart_item.id), method: :delete %>
      </div>
    </div>
  <% end %>
</div>

<script>
  const cartItems = document.getElementById('cart-items');

  cartItems.addEventListener('input', (event) => {
    if (event.target.classList.contains('quantity_input')) {
      const cartItemId = event.target.closest('.container').dataset.cartId;
      const newQuantity = event.target.value;

      fetch(`/cart/${cartItemId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ quantity: newQuantity })
      })
      .then(() => {
        console.log("cart updated");
        window.location.href = '<%= cart_index_path %>';
      })
      .catch((err) => {
        console.log(err);
      });
    }
  });
</script>

<h1>Total Price: <%= number_to_currency(@total, unit: "₹", precision: 2, delimiter: ",", format: "%u%n")%></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload',  defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<div class="navbar">
  <% unless role == "guest" %><button class="logout-button"><%= "logout" %></button><% end %>
  <%= link_to "login", login_path unless role != 'guest' %>
  <% unless current_page?(cart_index_path) %><%= link_to "cart", cart_index_path unless role != 'user' %><% end %>
  <% unless current_page?(root_path) %><button class="home-button">home</button><% end %>
  <div>  user: <%= role %></div>
</div>

<script>
    var logoutButton = document.querySelector('.logout-button');
    logoutButton.addEventListener('click', () => {window.location.href = '<%= user_logout_path %>';});

    var homeButton = document.querySelector('.home-button');
    homeButton.addEventListener('click', () => {window.location.href = '<%= root_path %>';});
</script>

app/views/user/login_form.html.erb
<%= form_tag user_login_path, method: :post do %>
    <div class="field">
    <%= label_tag :email %>
    <%= email_field_tag :email %>
    </div>

    <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    </div>

    <div class="actions">
    <%= submit_tag 'Log In' %>
    </div>

    <div>
        <p>if not registered</p><%= link_to "register", register_path %>
    </div>
<% end %>

app/views/user/new.html.erb
<%= form_for(@user, url: user_) do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
  
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <%= f.hidden_field :user_role %>
    
    <div class="actions">
      <%= f.submit %>
    </div>

    <div>
      <p>if alredy registered</p><%= link_to "login", login_path %>
    </div>
  <% end %>
  